name: War of the Ghosts
description: War of the Ghosts Blog 
baseurl: "/WarOfTheGhosts"
links:
    About:
        url: https://github.com/uoou/WarOfTheGhosts/blob/gh-pages/README.md
    Wiki:
        url: https://github.com/uoou/WarOfTheGhosts/wiki 
    GitHub:
        url: https://github.com/uoou/WarOfTheGhosts/
    Twitter:
        url: https://twitter.com/yemachine
    Book:
        url: /WarOfTheGhosts/book.html 
authors:
    simon:
        name: Simon J. Cook
        email: simonjohncook@gmail.com
    brad:
        name: Dr. Brad Hammer
        email: 
#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/
